# Generated by Django 5.2.6 on 2025-10-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificacion", "0002_item_texto_para_copiar"),
    ]

    operations = [
        migrations.AddField(
            model_name="orden",
            name="fecha_entrega_manual",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Entrega Manual"
            ),
        ),
    ]
