# Generated by Django 5.2.6 on 2025-10-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certificacion", "0003_orden_fecha_entrega_manual"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orden",
            name="fecha_entrega_manual",
        ),
    ]
